### ISSUE TITLE
Not sure how to implement

### ISSUE THREAD

**Issue by fgolman** [KodeMunkie/atomictext#2]
This is exactly what I've been looking for but I'm not familiar with your development environment (just have been using Arduino).

Please reach out to me and let me know.

Just really looking for a turnkey implementation on my Atom.

Thank you!

**Comment by KodeMunkie** [comment]
Hi, it's just a regular [PlatformIO](https://platformio.org/) project - just open the folder itself in PlatformIO. 
With your Atom connected, select the alien icon (PlatformIO icon) left side, select "Upload" (this should build automatically first, if it doesn't just click the "Build" option). Don't forget to set the constants in the main.cpp mentioned in the readme.
Hope this helps!

**Comment by fgolman** [comment]
I think so. I'm a newbie in this even though many years in systems and technology.

Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fgolman** [comment]
Well, now that I figured out PlatformIO and how launch it into the app, the build/upload failed. Here's the terminal session log. Perhaps there's a missing or incorrectly named library? Also, I've loaded this in my Arduino library folder ... maybe it should be elsewhere on my drive?

Thanks for your insight!


> Executing task: C:\Users\1123781\.platformio\penv\Scripts\pio.exe run --environment m5stack-core-esp32 <

Processing m5stack-core-esp32 (platform: espressif32; board: m5stick-c; framework: arduino)
------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stick-c.html
PLATFORM: Espressif 32 (2.0.0) > M5Stick-C
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10004.201016 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 28 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <M5Atom> 0.0.1
|   |-- <FastLED> 3.3.3
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|-- <FastLED> 3.3.3
|   |-- <SPI> 1.0
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <WiFi> 1.0
Building in release mode
Compiling .pio\build\m5stack-core-esp32\src\messageHandler.cpp.o
Archiving .pio\build\m5stack-core-esp32\libb94\libM5Atom.a
Compiling .pio\build\m5stack-core-esp32\lib500\WiFi\WiFiAP.cpp.o
src\messageHandler.cpp:19:28: fatal error: ESP32WebServer.h: No such file or directory

************************************************************************
* Looking for ESP32WebServer.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP32WebServer.h"
* Web  > Compiling .pio\build\m5stack-core-esp32\lib500\WiFi\WiFiClient.cpp.o
https://platformio.org/lib/search?query=header:ESP32WebServer.h
*
************************************************************************

compilation terminated.
Compiling .pio\build\m5stack-core-esp32\lib500\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib500\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib500\WiFi\WiFiSTA.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib500\WiFi\WiFiScan.cpp.o
*** [.pio\build\m5stack-core-esp32\src\messageHandler.cpp.o] Error 1
===================================== [FAILED] Took 4.85 seconds =====================================
The terminal process "C:\Users\1123781\.platformio\penv\Scripts\pio.exe 'run', '--environment', 'm5stack-core-esp32'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by fgolman** [comment]
Getting closer, figured out library dependency except it seems esp32webserver. Is there a specifc version or source you're using? 

Here's the run now:


Processing m5stack-core-esp32 (platform: espressif32; board: m5stick-c; framework: arduino)
-------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stick-c.html
PLATFORM: Espressif 32 (2.0.0) > M5Stick-C
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10004.201016 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 28 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <M5Atom> 0.0.1
|   |-- <FastLED> 3.3.3
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|-- <FastLED> 3.3.3
|   |-- <SPI> 1.0
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <WiFi> 1.0
Building in release mode
Compiling .pio\build\m5stack-core-esp32\src\messageHandler.cpp.o
src\messageHandler.cpp:19:28: fatal error: ESP32WebServer.h: No such file or directory

************************************************************************
* Looking for ESP32WebServer.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP32WebServer.h"
* Web  > https://platformio.org/lib/search?query=header:ESP32WebServer.h
*
************************************************************************

compilation terminated.
*** [.pio\build\m5stack-core-esp32\src\messageHandler.cpp.o] Error 1
===================================== [FAILED] Took 2.99 seconds =====================================
The terminal process "C:\Users\1123781\.platformio\penv\Scripts\pio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by KodeMunkie** [comment]
I'll have a check tonight but there is a dependency on that library. You need to import the the dependency in PlatformIO, not via the Arduino folder (since it doesn't look in your Arduino IDE library). You can do this via the PlatofrmIO IDE, there is an automatic option to fix it (or use the library/header browser) although I may also be able to do the same by adding the dependency in the platformio.ini and then you can update (no idea if this will work, but should do).

**Comment by KodeMunkie** [comment]
@fgolman can you try the [FixDeps code branch](https://github.com/KodeMunkie/atomictext/tree/FixDeps) I've put in the pull request for this issue and leave a comment here or on the pull request as to whether it works for you? 
I deleted my (already downloaded) lib dependencies and then my builds failed like yours, I added the new lines (in that request) and it then built fine.

**Comment by fgolman** [comment]
The FixDeps code branch seemed to compile just fine and works. BUT, no default message appears and I don't see the device on my network.

In addition, it would be wonderful to get the IP address the device grabs using Mark Garetz's code: https://github.com/MarkGaretz/ATOM-Matrix-Tally-Light.

**Comment by KodeMunkie** [comment]
Again I'll look later this evening but if I remember correctly no message
will be shown until it connects to your WiFi network.
mDNS is used to create a "atomictext.local" domain name on your network
(accessible by desktops, strangely Chrome/mobile devices don't seem to
support mDNS) that you can use instead of trying to find the IP.
I'll put some extra Serial logging in but feel free to submit a pull
request with Mark G's changes if you want.
I find that usually it's a typo in the WiFi constants that cause the
connection to fail and no message to be displayed (I guess you've no MAC
restrictions too).

**Comment by fgolman** [comment]
Based on your notes, I tried another WiFi access point and it worked! Including the local mDNS!

Now, in addition to the IP address (so we could have multiple devices on same network) how about single color display rather than cycling through rainbow.

Thank you for your assistance and explanations! Looking good now!

**Comment by KodeMunkie** [comment]
Please add your feature requests as new issues - feel free to submit code changes pull requests or I'll have a look at the feature issues when I get time (config options, for which single colour would fall under, is on my TODO list for this "quick and dirty" project)
